version: '3'
services:
  mysql-server-1:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0.13
    ports:
      - "3301:3306"
    command: ["mysqld","--server_id=1","--binlog_checksum=NONE","--sort-buffer-size=100M","--read_buffer_size=100M","--max_connections=256","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    volumes:
    - db_data1:/var/lib/mysql

  mysql-server-2:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0.13
    command: ["mysqld","--server_id=2","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3302:3306"
    volumes:
    - db_data2:/var/lib/mysql

  mysql-server-3:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0.13
    command: ["mysqld","--server_id=3","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3303:3306"
    volumes:
    - db_data3:/var/lib/mysql

  mysql-shell:
    env_file:
      - mysql-shell.env
    image: neumayer/mysql-shell-batch
    #command: ["sleep", "36000"]
    volumes:
        - ./scripts/:/scripts/
    depends_on:
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
  mysql-router:
    env_file:
      - mysql-router.env
    image: mysql/mysql-router:8.0.13
    ports:
      - "6446:6446"
    depends_on:
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
      - mysql-shell
    restart: on-failure
  admin:
    build:
      context: admin/
    tty: true
    command: >
      sh -c "while ! mysqladmin ping -h mysql-server-1 -uroot -pmysql --silent; do sleep 1; done;
      cd /tmp/test_db/;
      mysql -h mysql-server-1 -uroot -pmysql < employees.sql;"
    ports:
      - "2222:22"
    depends_on:
      - mysql-router
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
      - mysql-shell

volumes:
  db_data1:
  db_data2:
  db_data3: